version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.0-b6
  docker-executor:
    docker:
      - image: docker:18.06.3-ce-git
  smoke-test-executor:
    machine: true

commands:
  cached-checkout:
      description: "Checkout with caching"
      steps:
        - restore_cache:
            keys:
              - source-v1-{{ .Branch }}-{{ .Revision }}
              - source-v1-{{ .Branch }}-
              - source-v1-
        - checkout
        - save_cache:
            key: source-v1-{{ .Branch }}-{{ .Revision }}
            paths:
              - ".git"

  restore-maven-cache:
      description: "Calculate cache key and restore cache"
      steps:
        - run: 
            name: Calculate cache key from pom files
            command: |
              find . -type f -name "pom.xml" -exec sha256sum "{}" \; >> maven-dependency-cache.key
        - restore_cache:
            keys:
              - maven-dependencies-v2-{{ checksum "maven-dependency-cache.key" }}
              - maven-dependencies-v2-
        - run:
            name: Remove OpenNMS artifacts from cache
            command: |
              rm -rf ~/.m2/repository/org/opennms

  save-maven-cache:
    description: "Save Maven dependency cache"
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-v2-{{ checksum "maven-dependency-cache.key" }}

workflows:
  build-deploy:
    jobs:
      - build
      - build-horizon-oci:
          requires:
            - build
      - smoke-test:
          requires:
            - build

jobs:
  build:
    executor: build-executor
    # Building currently requires the xlarge containers in order for the webpack compilation
    # in the core/web-assets module to complete reliably
    resource_class: xlarge
    steps:
      - cached-checkout
      - restore-maven-cache
      - run:
          name: Compile
          command: |
            mvn clean -DskipTests=true
            ./compile.pl -DskipTests=true -Dbuild.skip.tarball=true
      - run:
          name: Build RPMs
          command: |
            ./makerpm.sh -a -d
      - save-maven-cache
      - store_artifacts:
          path: ~/project/target/rpm/RPMS/noarch
          destination: rpms
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  
  build-horizon-oci:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: 
          name: Switch to Horizon Docker build environment
          command: |
            cd project/opennms-container/horizon
      - run:
          name: Fetchg RPMs to install Horizon
          command: |
            cp target/rpm/RPMS/noarch/opennms-core-*.noarch.rpm rpms
            cp target/rpm/RPMS/noarch/opennms-webapp-jetty-*.noarch.rpms
            cp target/rpm/RPMS/noarch/opennms-webapp-hawtio-*.noarch.rpms 
      - run:
          name: Build Horizon Docker container image
          command: |
            cd horizon
            ./build_container_image.sh
      - store_artifacts:
          path: ~/project/opennms-container/horizon/images/container.oci
          destination: horizon

  smoke-test:
    executor: smoke-test-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore-maven-cache
      - run:
          name: Smoke Tests
          command: |
            .circleci/scripts/smoke.sh

